{-
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
-}

fibs = 1:2:[m + n | (m, n) <- zip fibs (tail fibs)]

euler2 = sum $ filter even $ takeWhile (<= 4000000) fibs

--

-- http://projecteuler.net/overview=002
evenFib 0 = 2
evenFib 1 = 8
evenFib n = 4 * evenFib (n-1) + evenFib(n-2)

euler2' = sum $ takeWhile (<= 4000000) $ map evenFib [0..]
